import type { Product } from "./products";

const sizes = ["S", "M", "L", "XL"];

function variants(sku: string) {
  return sizes.map((size) => ({
    sku: `${sku}-${size}`,
    size,
    stock: 25,
    active: true
  }));
}

/**
 * Dataset 37 sản phẩm Flat-lay (thuần trang phục, không dính người, nền trắng/studio)
 * Thiết kế cho thương mại điện tử, Virtual Try-On (FASHN AI) và AI Stylist.
 * Mỗi thiết kế có nhiều màu (liên kết qua groupCode), mỗi màu có SKU và hình ảnh đúng màu sắc đó.
 */
export const flatlayProducts: Product[] = [
  // =========================================================================
  // 1. Aura Column Bodycon Maxi Dress (3 màu: Đen, Đỏ rượu, Trắng kem)
  // =========================================================================
  {
    id: "lsoul-aura-maxi-dress-black",
    sku: "DR-AURA-MAXI-BLK",
    groupCode: "DR-AURA-MAXI",
    name: "Aura Bodycon Maxi Dress",
    subtitle: "Đầm bodycon dáng dài sát nách tôn eo ôm trọn đường cong (Đen)",
    category: "dress",
    type: "bodycon-dress",
    gender: "women",
    price: 1850000,
    color: "Đen",
    colorFamily: "black",
    colorHex: "#111111",
    sizes,
    stock: 50,
    stockTracked: true,
    variants: variants("DR-AURA-MAXI-BLK"),
    image: "/products/dress-bodycon-maxi-black.jpg",
    hoverImage: "/products/dress-bodycon-maxi-black.jpg",
    images: ["/products/dress-bodycon-maxi-black.jpg"],
    style: ["minimal", "sexy", "glam", "statement"],
    occasion: ["đi tiệc", "hẹn hò", "sự kiện buổi tối"],
    material: "Thun cotton dệt kim co giãn 4 chiều cao cấp",
    fit: "Fitted column bodycon",
    silhouette: "bodycon",
    lengthClass: "maxi",
    neckline: "round",
    sleeveLength: "sleeveless",
    featured: true,
    isNew: true,
    active: true,
    sourceType: "retailer-corroborated",
    sourceUpdatedAt: "2026-10-02",
    tryOnCategory: "one-pieces",
    tryOnPhotoType: "flat-lay",
    tryOnImage: "/products/dress-bodycon-maxi-black.jpg",
    pattern: "solid",
    season: ["spring", "summer", "autumn"],
    formality: 4,
    warmth: 2,
    stretch: 4,
    coverage: 4,
    colorTemperature: "neutral",
    styleKeywords: ["váy body dài", "đầm body dài", "bodycon", "maxi", "đen", "tôn dáng", "đi tiệc", "hẹn hò"],
    aiSearchText: "đầm bodycon dáng dài màu đen váy body dài ôm sát tôn dáng đi tiệc hẹn hò sexy minimal",
    analyzerReady: true
  },
  {
    id: "lsoul-aura-maxi-dress-red",
    sku: "DR-AURA-MAXI-RED",
    groupCode: "DR-AURA-MAXI",
    name: "Aura Bodycon Maxi Dress",
    subtitle: "Đầm bodycon dáng dài sát nách sang trọng quý phái (Đỏ rượu)",
    category: "dress",
    type: "bodycon-dress",
    gender: "women",
    price: 1850000,
    color: "Đỏ rượu",
    colorFamily: "red",
    colorHex: "#6B1D2F",
    sizes,
    stock: 50,
    stockTracked: true,
    variants: variants("DR-AURA-MAXI-RED"),
    image: "/products/dress-bodycon-maxi-red.jpg",
    hoverImage: "/products/dress-bodycon-maxi-red.jpg",
    images: ["/products/dress-bodycon-maxi-red.jpg"],
    style: ["glam", "sexy", "statement"],
    occasion: ["đi tiệc", "hẹn hò", "sự kiện buổi tối"],
    material: "Thun cotton dệt kim co giãn 4 chiều cao cấp",
    fit: "Fitted column bodycon",
    silhouette: "bodycon",
    lengthClass: "maxi",
    neckline: "round",
    sleeveLength: "sleeveless",
    featured: true,
    isNew: true,
    active: true,
    sourceType: "retailer-corroborated",
    sourceUpdatedAt: "2026-10-02",
    tryOnCategory: "one-pieces",
    tryOnPhotoType: "flat-lay",
    tryOnImage: "/products/dress-bodycon-maxi-red.jpg",
    pattern: "solid",
    season: ["spring", "summer", "autumn"],
    formality: 5,
    warmth: 2,
    stretch: 4,
    coverage: 4,
    colorTemperature: "warm",
    styleKeywords: ["váy body dài", "đầm body dài đỏ", "đỏ rượu", "burgundy", "bodycon", "maxi", "đi tiệc"],
    aiSearchText: "đầm bodycon dáng dài màu đỏ rượu váy body dài ôm sát đi tiệc hẹn hò sang trọng quyến rũ",
    analyzerReady: true
  },
  {
    id: "lsoul-aura-maxi-dress-white",
    sku: "DR-AURA-MAXI-WHT",
    groupCode: "DR-AURA-MAXI",
    name: "Aura Bodycon Maxi Dress",
    subtitle: "Đầm bodycon dáng dài tay dài thanh lịch màu trắng ngà (Trắng kem)",
    category: "dress",
    type: "bodycon-dress",
    gender: "women",
    price: 1890000,
    color: "Trắng kem",
    colorFamily: "white",
    colorHex: "#F7F6F2",
    sizes,
    stock: 45,
    stockTracked: true,
    variants: variants("DR-AURA-MAXI-WHT"),
    image: "/products/dress-bodycon-maxi-white.jpg",
    hoverImage: "/products/dress-bodycon-maxi-white.jpg",
    images: ["/products/dress-bodycon-maxi-white.jpg"],
    style: ["minimal", "elegant", "romantic"],
    occasion: ["hẹn hò", "đi tiệc", "sự kiện"],
    material: "Thun dệt kim mềm mịn co giãn cao cấp",
    fit: "Fitted column bodycon",
    silhouette: "bodycon",
    lengthClass: "maxi",
    neckline: "round",
    sleeveLength: "long",
    featured: true,
    isNew: true,
    active: true,
    sourceType: "retailer-corroborated",
    sourceUpdatedAt: "2026-10-02",
    tryOnCategory: "one-pieces",
    tryOnPhotoType: "flat-lay",
    tryOnImage: "/products/dress-bodycon-maxi-white.jpg",
    pattern: "solid",
    season: ["spring", "autumn", "winter"],
    formality: 4,
    warmth: 3,
    stretch: 4,
    coverage: 5,
    colorTemperature: "neutral",
    styleKeywords: ["váy body dài trắng", "đầm body dài", "trắng kem", "bodycon", "maxi", "thanh lịch"],
    aiSearchText: "đầm bodycon dáng dài màu trắng kem váy body dài tay dài thanh lịch hẹn hò minimal",
    analyzerReady: true
  },

  // =========================================================================
  // 2. Vesper Satin Boned Corset Top (3 màu: Đen, Trắng, Đỏ)
  // =========================================================================
  {
    id: "lsoul-vesper-corset-black",
    sku: "TP-VESPER-CORSET-BLK",
    groupCode: "TP-VESPER-CORSET",
    name: "Vesper Satin Corset Top",
    subtitle: "Áo corset gọng định hình siết eo cúp ngực chất lụa satin (Đen)",
    category: "tops",
    type: "corset",
    gender: "women",
    price: 1350000,
    color: "Đen",
    colorFamily: "black",
    colorHex: "#151515",
    sizes,
    stock: 60,
    stockTracked: true,
    variants: variants("TP-VESPER-CORSET-BLK"),
    image: "/products/top-corset-satin-black.jpg",
    hoverImage: "/products/top-corset-satin-black.jpg",
    images: ["/products/top-corset-satin-black.jpg"],
    style: ["corset", "sexy", "glam", "Y2K"],
    occasion: ["đi tiệc", "hẹn hò", "bar", "clubbing"],
    material: "Satin cao cấp phối gọng định hình",
    fit: "Structured boned corset fit",
    silhouette: "fitted",
    lengthClass: "crop",
    neckline: "sweetheart",
    sleeveLength: "sleeveless",
    featured: true,
    isNew: true,
    active: true,
    sourceType: "retailer-corroborated",
    sourceUpdatedAt: "2026-10-02",
    tryOnCategory: "tops",
    tryOnPhotoType: "flat-lay",
    tryOnImage: "/products/top-corset-satin-black.jpg",
    pattern: "solid",
    season: ["spring", "summer", "autumn"],
    formality: 4,
    warmth: 1,
    stretch: 2,
    coverage: 2,
    colorTemperature: "neutral",
    styleKeywords: ["áo corset đen", "corset siết eo", "cúp ngực", "gọng định hình", "đi tiệc"],
    aiSearchText: "áo corset đen gọng định hình siết eo cúp ngực lụa satin đi tiệc bar hẹn hò",
    analyzerReady: true
  },
  {
    id: "lsoul-vesper-corset-white",
    sku: "TP-VESPER-CORSET-WHT",
    groupCode: "TP-VESPER-CORSET",
    name: "Vesper Satin Corset Top",
    subtitle: "Áo corset gọng định hình đan dây cúp ngực phối nơ (Trắng)",
    category: "tops",
    type: "corset",
    gender: "women",
    price: 1350000,
    color: "Trắng",
    colorFamily: "white",
    colorHex: "#FFFFFF",
    sizes,
    stock: 55,
    stockTracked: true,
    variants: variants("TP-VESPER-CORSET-WHT"),
    image: "/products/top-corset-satin-white.jpg",
    hoverImage: "/products/top-corset-satin-white.jpg",
    images: ["/products/top-corset-satin-white.jpg"],
    style: ["corset", "nữ tính", "romantic", "Y2K"],
    occasion: ["đi tiệc", "hẹn hò", "đi chơi"],
    material: "Satin lụa mềm phối gọng định hình và dây đan ngực",
    fit: "Structured boned corset fit",
    silhouette: "fitted",
    lengthClass: "crop",
    neckline: "sweetheart",
    sleeveLength: "sleeveless",
    featured: true,
    isNew: true,
    active: true,
    sourceType: "retailer-corroborated",
    sourceUpdatedAt: "2026-10-02",
    tryOnCategory: "tops",
    tryOnPhotoType: "flat-lay",
    tryOnImage: "/products/top-corset-satin-white.jpg",
    pattern: "solid",
    season: ["spring", "summer", "autumn"],
    formality: 4,
    warmth: 1,
    stretch: 2,
    coverage: 2,
    colorTemperature: "neutral",
    styleKeywords: ["áo corset trắng", "corset hai dây", "đan dây", "gọng định hình", "nữ tính"],
    aiSearchText: "áo corset trắng hai dây đan dây trước gọng định hình siết eo lụa satin đi tiệc hẹn hò",
    analyzerReady: true
  },
  {
    id: "lsoul-vesper-corset-red",
    sku: "TP-VESPER-CORSET-RED",
    groupCode: "TP-VESPER-CORSET",
    name: "Vesper Satin Corset Top",
    subtitle: "Áo corset gọng định hình đan dây cúp ngực quyến rũ (Đỏ rượu)",
    category: "tops",
    type: "corset",
    gender: "women",
    price: 1350000,
    color: "Đỏ",
    colorFamily: "red",
    colorHex: "#9B1B30",
    sizes,
    stock: 50,
    stockTracked: true,
    variants: variants("TP-VESPER-CORSET-RED"),
    image: "/products/top-corset-satin-red.jpg",
    hoverImage: "/products/top-corset-satin-red.jpg",
    images: ["/products/top-corset-satin-red.jpg"],
    style: ["corset", "sexy", "statement", "glam"],
    occasion: ["đi tiệc", "concert", "bar", "hẹn hò"],
    material: "Satin lụa đỏ thắm phối gọng định hình và dây đan ngực",
    fit: "Structured boned corset fit",
    silhouette: "fitted",
    lengthClass: "crop",
    neckline: "sweetheart",
    sleeveLength: "sleeveless",
    featured: true,
    isNew: true,
    active: true,
    sourceType: "retailer-corroborated",
    sourceUpdatedAt: "2026-10-02",
    tryOnCategory: "tops",
    tryOnPhotoType: "flat-lay",
    tryOnImage: "/products/top-corset-satin-red.jpg",
    pattern: "solid",
    season: ["spring", "summer", "autumn"],
    formality: 4,
    warmth: 1,
    stretch: 2,
    coverage: 2,
    colorTemperature: "warm",
    styleKeywords: ["áo corset đỏ", "corset đan dây", "đỏ rượu", "cúp ngực", "nổi bật"],
    aiSearchText: "áo corset đỏ rượu đan dây cúp ngực siết eo satin nổi bật đi tiệc concert sexy",
    analyzerReady: true
  },

  // =========================================================================
  // 3. Tennis High-Waist Pleated Mini Skirt (3 màu: Đen, Trắng, Xám)
  // =========================================================================
  {
    id: "lsoul-tennis-pleated-skirt-black",
    sku: "SK-TENNIS-PLEAT-BLK",
    groupCode: "SK-TENNIS-PLEAT",
    name: "Tennis Pleated Mini Skirt",
    subtitle: "Chân váy ngắn xếp ly tennis cạp cao hack dáng năng động (Đen)",
    category: "bottoms",
    type: "skirt",
    gender: "women",
    price: 890000,
    color: "Đen",
    colorFamily: "black",
    colorHex: "#111111",
    sizes,
    stock: 65,
    stockTracked: true,
    variants: variants("SK-TENNIS-PLEAT-BLK"),
    image: "/products/skirt-pleated-mini-black.jpg",
    hoverImage: "/products/skirt-pleated-mini-black.jpg",
    images: ["/products/skirt-pleated-mini-black.jpg"],
    style: ["preppy", "Y2K", "nữ tính", "sporty"],
    occasion: ["đi chơi", "đi cafe", "hẹn hò", "concert"],
    material: "Vải tuyết mưa đứng phom cao cấp có quần bảo hộ trong",
    fit: "High-waist A-line pleated fit",
    silhouette: "a-line",
    lengthClass: "mini",
    waistRise: "high",
    featured: true,
    isNew: true,
    active: true,
    sourceType: "retailer-corroborated",
    sourceUpdatedAt: "2026-10-02",
    tryOnCategory: "bottoms",
    tryOnPhotoType: "flat-lay",
    tryOnImage: "/products/skirt-pleated-mini-black.jpg",
    pattern: "pleated",
    season: ["spring", "summer", "autumn"],
    formality: 2,
    warmth: 2,
    stretch: 1,
    coverage: 2,
    colorTemperature: "neutral",
    styleKeywords: ["chân váy đen", "chân váy xếp ly", "tennis skirt", "cạp cao", "ngắn", "hack dáng"],
    aiSearchText: "chân váy đen xếp ly tennis cạp cao dáng xòe ngắn nữ tính Y2K đi chơi",
    analyzerReady: true
  },
  {
    id: "lsoul-tennis-pleated-skirt-white",
    sku: "SK-TENNIS-PLEAT-WHT",
    groupCode: "SK-TENNIS-PLEAT",
    name: "Tennis Pleated Mini Skirt",
    subtitle: "Chân váy ngắn xếp ly tennis cạp cao tôn dáng thanh lịch (Trắng)",
    category: "bottoms",
    type: "skirt",
    gender: "women",
    price: 890000,
    color: "Trắng",
    colorFamily: "white",
    colorHex: "#FFFFFF",
    sizes,
    stock: 60,
    stockTracked: true,
    variants: variants("SK-TENNIS-PLEAT-WHT"),
    image: "/products/skirt-pleated-mini-white.jpg",
    hoverImage: "/products/skirt-pleated-mini-white.jpg",
    images: ["/products/skirt-pleated-mini-white.jpg"],
    style: ["preppy", "romantic", "nữ tính", "sporty"],
    occasion: ["đi chơi", "đi cafe", "hẹn hò"],
    material: "Vải tuyết mưa đứng phom cao cấp có quần bảo hộ trong",
    fit: "High-waist A-line pleated fit",
    silhouette: "a-line",
    lengthClass: "mini",
    waistRise: "high",
    featured: true,
    isNew: true,
    active: true,
    sourceType: "retailer-corroborated",
    sourceUpdatedAt: "2026-10-02",
    tryOnCategory: "bottoms",
    tryOnPhotoType: "flat-lay",
    tryOnImage: "/products/skirt-pleated-mini-white.jpg",
    pattern: "pleated",
    season: ["spring", "summer", "autumn"],
    formality: 2,
    warmth: 2,
    stretch: 1,
    coverage: 2,
    colorTemperature: "neutral",
    styleKeywords: ["chân váy trắng", "chân váy xếp ly", "tennis skirt", "trắng tinh khôi", "cạp cao"],
    aiSearchText: "chân váy trắng xếp ly tennis cạp cao dáng chữ A ngắn nữ tính preppy đi cafe",
    analyzerReady: true
  },
  {
    id: "lsoul-tennis-pleated-skirt-gray",
    sku: "SK-TENNIS-PLEAT-GRY",
    groupCode: "SK-TENNIS-PLEAT",
    name: "Tennis Pleated Mini Skirt",
    subtitle: "Chân váy ngắn xếp ly tennis cạp cao chuẩn style Preppy Y2K (Xám)",
    category: "bottoms",
    type: "skirt",
    gender: "women",
    price: 890000,
    color: "Xám",
    colorFamily: "gray",
    colorHex: "#707372",
    sizes,
    stock: 45,
    stockTracked: true,
    variants: variants("SK-TENNIS-PLEAT-GRY"),
    image: "/products/skirt-pleated-grey.jpg",
    hoverImage: "/products/skirt-pleated-grey.jpg",
    images: ["/products/skirt-pleated-grey.jpg"],
    style: ["preppy", "Y2K", "streetwear"],
    occasion: ["đi học", "đi chơi", "cafe"],
    material: "Vải dệt tổng hợp đứng phom có lót",
    fit: "High-waist A-line pleated fit",
    silhouette: "a-line",
    lengthClass: "mini",
    waistRise: "high",
    featured: false,
    isNew: true,
    active: true,
    sourceType: "retailer-corroborated",
    sourceUpdatedAt: "2026-10-02",
    tryOnCategory: "bottoms",
    tryOnPhotoType: "flat-lay",
    tryOnImage: "/products/skirt-pleated-grey.jpg",
    pattern: "pleated",
    season: ["spring", "summer", "autumn"],
    formality: 2,
    warmth: 2,
    stretch: 1,
    coverage: 2,
    colorTemperature: "cool",
    styleKeywords: ["chân váy xám", "chân váy xếp ly", "preppy", "Y2K", "xám khói"],
    aiSearchText: "chân váy xám ngắn xếp ly tennis cạp cao preppy Y2K năng động",
    analyzerReady: true
  },

  // =========================================================================
  // 4. Atelier Tailored Wide-Leg Trousers (3 màu: Đen, Be kem, Nâu đất)
  // =========================================================================
  {
    id: "lsoul-atelier-wide-trousers-black",
    sku: "PT-ATELIER-WIDE-BLK",
    groupCode: "PT-ATELIER-WIDE",
    name: "Atelier Wide-Leg Trousers",
    subtitle: "Quần tây ống suông rộng cạp cao xếp ly đôi tôn dáng dài miên man (Đen)",
    category: "bottoms",
    type: "trousers",
    gender: "women",
    price: 1450000,
    color: "Đen",
    colorFamily: "black",
    colorHex: "#101010",
    sizes,
    stock: 50,
    stockTracked: true,
    variants: variants("PT-ATELIER-WIDE-BLK"),
    image: "/products/pants-tailored-wide-black.jpg",
    hoverImage: "/products/pants-tailored-wide-black.jpg",
    images: ["/products/pants-tailored-wide-black.jpg"],
    style: ["minimal", "tailored", "công sở", "chic"],
    occasion: ["đi làm", "sự kiện", "đi cafe", "hẹn hò"],
    material: "Vải đũi pha len chéo đứng dáng chống nhăn",
    fit: "High-rise relaxed wide-leg",
    silhouette: "wide-leg",
    lengthClass: "maxi",
    waistRise: "high",
    featured: true,
    isNew: true,
    active: true,
    sourceType: "retailer-corroborated",
    sourceUpdatedAt: "2026-10-02",
    tryOnCategory: "bottoms",
    tryOnPhotoType: "flat-lay",
    tryOnImage: "/products/pants-tailored-wide-black.jpg",
    pattern: "solid",
    season: ["spring", "summer", "autumn", "winter"],
    formality: 4,
    warmth: 3,
    stretch: 1,
    coverage: 5,
    colorTemperature: "neutral",
    styleKeywords: ["quần tây đen", "quần ống suông", "quần cạp cao", "quần âu", "hack chân", "tối giản"],
    aiSearchText: "quần tây đen ống suông cạp cao xếp ly hack dáng thanh lịch tối giản đi làm sự kiện",
    analyzerReady: true
  },
  {
    id: "lsoul-atelier-wide-trousers-beige",
    sku: "PT-ATELIER-WIDE-BEI",
    groupCode: "PT-ATELIER-WIDE",
    name: "Atelier Wide-Leg Trousers",
    subtitle: "Quần tây ống suông rộng cạp cao tone be ngà sang chảnh (Be kem)",
    category: "bottoms",
    type: "trousers",
    gender: "women",
    price: 1450000,
    color: "Be kem",
    colorFamily: "beige",
    colorHex: "#EFEBD9",
    sizes,
    stock: 45,
    stockTracked: true,
    variants: variants("PT-ATELIER-WIDE-BEI"),
    image: "/products/pants-tailored-wide-beige.jpg",
    hoverImage: "/products/pants-tailored-wide-beige.jpg",
    images: ["/products/pants-tailored-wide-beige.jpg"],
    style: ["minimal", "quiet luxury", "công sở", "chic"],
    occasion: ["đi làm", "đi cafe", "hẹn hò"],
    material: "Vải đũi pha len chéo đứng dáng chống nhăn",
    fit: "High-rise relaxed wide-leg",
    silhouette: "wide-leg",
    lengthClass: "maxi",
    waistRise: "high",
    featured: true,
    isNew: true,
    active: true,
    sourceType: "retailer-corroborated",
    sourceUpdatedAt: "2026-10-02",
    tryOnCategory: "bottoms",
    tryOnPhotoType: "flat-lay",
    tryOnImage: "/products/pants-tailored-wide-beige.jpg",
    pattern: "solid",
    season: ["spring", "summer", "autumn", "winter"],
    formality: 4,
    warmth: 3,
    stretch: 1,
    coverage: 5,
    colorTemperature: "warm",
    styleKeywords: ["quần tây be", "quần màu kem", "ống suông", "cạp cao", "quiet luxury"],
    aiSearchText: "quần tây be kem ống suông cạp cao thanh lịch sang trọng đi làm đi chơi",
    analyzerReady: true
  },
  {
    id: "lsoul-atelier-wide-trousers-brown",
    sku: "PT-ATELIER-WIDE-BRN",
    groupCode: "PT-ATELIER-WIDE",
    name: "Atelier Wide-Leg Trousers",
    subtitle: "Quần tây ống rộng cạp cao tone nâu chocolate thanh lịch (Nâu đất)",
    category: "bottoms",
    type: "trousers",
    gender: "women",
    price: 1450000,
    color: "Nâu đất",
    colorFamily: "brown",
    colorHex: "#543D2B",
    sizes,
    stock: 40,
    stockTracked: true,
    variants: variants("PT-ATELIER-WIDE-BRN"),
    image: "/products/pants-trousers-brown.jpg",
    hoverImage: "/products/pants-trousers-brown.jpg",
    images: ["/products/pants-trousers-brown.jpg"],
    style: ["minimal", "vintage", "công sở"],
    occasion: ["đi làm", "mua sắm", "cafe"],
    material: "Vải đũi pha len chéo đứng dáng",
    fit: "High-rise relaxed wide-leg",
    silhouette: "wide-leg",
    lengthClass: "maxi",
    waistRise: "high",
    featured: false,
    isNew: true,
    active: true,
    sourceType: "retailer-corroborated",
    sourceUpdatedAt: "2026-10-02",
    tryOnCategory: "bottoms",
    tryOnPhotoType: "flat-lay",
    tryOnImage: "/products/pants-trousers-brown.jpg",
    pattern: "solid",
    season: ["autumn", "winter"],
    formality: 4,
    warmth: 3,
    stretch: 1,
    coverage: 5,
    colorTemperature: "warm",
    styleKeywords: ["quần nâu", "ống suông", "quần cạp cao", "vintage"],
    aiSearchText: "quần tây nâu ống rộng cạp cao mùa thu đông cổ điển thanh lịch",
    analyzerReady: true
  },

  // =========================================================================
  // 5. Minimalist Tailored Blazer (2 màu: Đen, Be kem)
  // =========================================================================
  {
    id: "lsoul-tailored-blazer-black",
    sku: "BZ-MINIMAL-SUIT-BLK",
    groupCode: "BZ-MINIMAL-SUIT",
    name: "Minimalist Tailored Blazer",
    subtitle: "Áo khoác blazer cắt may chuẩn form vai quyền lực tôn dáng (Đen)",
    category: "outerwear",
    type: "blazer",
    gender: "women",
    price: 2450000,
    color: "Đen",
    colorFamily: "black",
    colorHex: "#121212",
    sizes,
    stock: 40,
    stockTracked: true,
    variants: variants("BZ-MINIMAL-SUIT-BLK"),
    image: "/products/blazer-tailored-black.jpg",
    hoverImage: "/products/blazer-tailored-black.jpg",
    images: ["/products/blazer-tailored-black.jpg"],
    style: ["tailored", "công sở", "edgy", "chic"],
    occasion: ["sự kiện", "đi làm", "đi tiệc", "hẹn hò"],
    material: "Vải dệt wool-blend cao cấp có đệm vai và lót lụa habutai",
    fit: "Tailored structured fit",
    silhouette: "structured",
    lengthClass: "midi",
    neckline: "lapel",
    sleeveLength: "long",
    featured: true,
    isNew: true,
    active: true,
    sourceType: "retailer-corroborated",
    sourceUpdatedAt: "2026-10-02",
    tryOnCategory: "tops",
    tryOnPhotoType: "flat-lay",
    tryOnImage: "/products/blazer-tailored-black.jpg",
    pattern: "solid",
    season: ["spring", "autumn", "winter"],
    formality: 5,
    warmth: 4,
    stretch: 1,
    coverage: 5,
    colorTemperature: "neutral",
    styleKeywords: ["áo blazer đen", "áo khoác vest", "blazer độn vai", "công sở", "sang trọng"],
    aiSearchText: "áo blazer đen cắt may có đệm vai lót lụa cao cấp thanh lịch quyền lực đi làm sự kiện",
    analyzerReady: true
  },
  {
    id: "lsoul-tailored-blazer-beige",
    sku: "BZ-MINIMAL-SUIT-BEI",
    groupCode: "BZ-MINIMAL-SUIT",
    name: "Minimalist Tailored Blazer",
    subtitle: "Áo khoác blazer cắt may chuẩn form tone kem thanh lịch quý phái (Be kem)",
    category: "outerwear",
    type: "blazer",
    gender: "women",
    price: 2450000,
    color: "Be kem",
    colorFamily: "beige",
    colorHex: "#EFEBD9",
    sizes,
    stock: 35,
    stockTracked: true,
    variants: variants("BZ-MINIMAL-SUIT-BEI"),
    image: "/products/blazer-tailored-beige.jpg",
    hoverImage: "/products/blazer-tailored-beige.jpg",
    images: ["/products/blazer-tailored-beige.jpg"],
    style: ["quiet luxury", "công sở", "chic", "thanh lịch"],
    occasion: ["sự kiện", "đi làm", "hẹn hò", "đi cafe"],
    material: "Vải dệt wool-blend cao cấp có đệm vai và lót lụa habutai",
    fit: "Tailored structured fit",
    silhouette: "structured",
    lengthClass: "midi",
    neckline: "lapel",
    sleeveLength: "long",
    featured: true,
    isNew: true,
    active: true,
    sourceType: "retailer-corroborated",
    sourceUpdatedAt: "2026-10-02",
    tryOnCategory: "tops",
    tryOnPhotoType: "flat-lay",
    tryOnImage: "/products/blazer-tailored-beige.jpg",
    pattern: "solid",
    season: ["spring", "autumn", "winter"],
    formality: 5,
    warmth: 4,
    stretch: 1,
    coverage: 5,
    colorTemperature: "warm",
    styleKeywords: ["áo blazer be", "blazer màu kem", "áo khoác vest be", "quiet luxury"],
    aiSearchText: "áo blazer be kem độn vai cao cấp phong cách quiet luxury thanh lịch sự kiện",
    analyzerReady: true
  },

  // =========================================================================
  // 6. Ribbed Square-Neck Knit Crop Top (3 màu: Đen, Trắng, Nâu)
  // =========================================================================
  {
    id: "lsoul-ribbed-croptop-black",
    sku: "TP-RIBBED-CROP-BLK",
    groupCode: "TP-RIBBED-CROP",
    name: "Ribbed Square-Neck Crop Top",
    subtitle: "Áo croptop dệt kim tăm cổ vuông khoe xương quai xanh (Đen)",
    category: "tops",
    type: "crop-top",
    gender: "women",
    price: 680000,
    color: "Đen",
    colorFamily: "black",
    colorHex: "#111111",
    sizes,
    stock: 70,
    stockTracked: true,
    variants: variants("TP-RIBBED-CROP-BLK"),
    image: "/products/top-ribbed-crop-black.jpg",
    hoverImage: "/products/top-ribbed-crop-black.jpg",
    images: ["/products/top-ribbed-crop-black.jpg"],
    style: ["minimal", "Y2K", "năng động"],
    occasion: ["đi chơi", "đi cafe", "đi học", "hẹn hò"],
    material: "Len dệt kim tăm co giãn 4 chiều mềm mịn",
    fit: "Fitted ribbed crop",
    silhouette: "fitted",
    lengthClass: "crop",
    neckline: "square",
    sleeveLength: "long",
    featured: true,
    isNew: true,
    active: true,
    sourceType: "retailer-corroborated",
    sourceUpdatedAt: "2026-10-02",
    tryOnCategory: "tops",
    tryOnPhotoType: "flat-lay",
    tryOnImage: "/products/top-ribbed-crop-black.jpg",
    pattern: "ribbed",
    season: ["spring", "autumn", "winter"],
    formality: 2,
    warmth: 3,
    stretch: 5,
    coverage: 3,
    colorTemperature: "neutral",
    styleKeywords: ["áo croptop đen", "cổ vuông", "dệt kim", "tay dài", "ôm body"],
    aiSearchText: "áo croptop đen dệt kim tăm cổ vuông tay dài ôm body tôn dáng đi chơi cafe",
    analyzerReady: true
  },
  {
    id: "lsoul-ribbed-croptop-white",
    sku: "TP-RIBBED-CROP-WHT",
    groupCode: "TP-RIBBED-CROP",
    name: "Ribbed Square-Neck Crop Top",
    subtitle: "Áo croptop dệt kim tăm cổ vuông trẻ trung quyến rũ (Trắng)",
    category: "tops",
    type: "crop-top",
    gender: "women",
    price: 680000,
    color: "Trắng",
    colorFamily: "white",
    colorHex: "#FFFFFF",
    sizes,
    stock: 65,
    stockTracked: true,
    variants: variants("TP-RIBBED-CROP-WHT"),
    image: "/products/top-ribbed-crop-white.jpg",
    hoverImage: "/products/top-ribbed-crop-white.jpg",
    images: ["/products/top-ribbed-crop-white.jpg"],
    style: ["minimal", "Y2K", "nữ tính"],
    occasion: ["đi chơi", "đi cafe", "hẹn hò"],
    material: "Len dệt kim tăm co giãn 4 chiều mềm mịn",
    fit: "Fitted ribbed crop",
    silhouette: "fitted",
    lengthClass: "crop",
    neckline: "square",
    sleeveLength: "short",
    featured: false,
    isNew: true,
    active: true,
    sourceType: "retailer-corroborated",
    sourceUpdatedAt: "2026-10-02",
    tryOnCategory: "tops",
    tryOnPhotoType: "flat-lay",
    tryOnImage: "/products/top-ribbed-crop-white.jpg",
    pattern: "ribbed",
    season: ["spring", "summer"],
    formality: 2,
    warmth: 2,
    stretch: 5,
    coverage: 2,
    colorTemperature: "neutral",
    styleKeywords: ["áo croptop trắng", "áo thun trắng", "cổ vuông", "năng động"],
    aiSearchText: "áo croptop trắng dệt kim ôm body trẻ trung năng động đi cafe đi chơi",
    analyzerReady: true
  },
  {
    id: "lsoul-ribbed-croptop-beige",
    sku: "TP-RIBBED-CROP-BEI",
    groupCode: "TP-RIBBED-CROP",
    name: "Ribbed Square-Neck Crop Top",
    subtitle: "Áo croptop dệt kim tăm ôm dáng tone be ấm áp (Be ấm)",
    category: "tops",
    type: "crop-top",
    gender: "women",
    price: 680000,
    color: "Be",
    colorFamily: "beige",
    colorHex: "#D8C9B4",
    sizes,
    stock: 50,
    stockTracked: true,
    variants: variants("TP-RIBBED-CROP-BEI"),
    image: "/products/top-ribbed-crop-beige.jpg",
    hoverImage: "/products/top-ribbed-crop-beige.jpg",
    images: ["/products/top-ribbed-crop-beige.jpg"],
    style: ["minimal", "quiet luxury"],
    occasion: ["đi chơi", "đi cafe"],
    material: "Len dệt kim tăm co giãn 4 chiều mềm mịn",
    fit: "Fitted ribbed crop",
    silhouette: "fitted",
    lengthClass: "crop",
    neckline: "round",
    sleeveLength: "short",
    featured: false,
    isNew: true,
    active: true,
    sourceType: "retailer-corroborated",
    sourceUpdatedAt: "2026-10-02",
    tryOnCategory: "tops",
    tryOnPhotoType: "flat-lay",
    tryOnImage: "/products/top-ribbed-crop-beige.jpg",
    pattern: "solid",
    season: ["spring", "summer"],
    formality: 2,
    warmth: 2,
    stretch: 5,
    coverage: 2,
    colorTemperature: "warm",
    styleKeywords: ["áo thun be", "croptop be", "tối giản"],
    aiSearchText: "áo thun croptop màu be kem mềm mại ôm body tối giản",
    analyzerReady: true
  },

  // =========================================================================
  // 7. Silk Slip Midi Dress Xẻ Tà (3 màu: Đen, Đỏ burgundy, Xanh navy)
  // =========================================================================
  {
    id: "lsoul-silk-slip-dress-black",
    sku: "DR-SILK-SLIP-BLK",
    groupCode: "DR-SILK-SLIP",
    name: "Silk Slip Midi Dress",
    subtitle: "Đầm lụa hai dây xẻ tà quyến rũ sang trọng cho buổi tối lãng mạn (Đen)",
    category: "dress",
    type: "midi-dress",
    gender: "women",
    price: 1950000,
    color: "Đen",
    colorFamily: "black",
    colorHex: "#111111",
    sizes,
    stock: 45,
    stockTracked: true,
    variants: variants("DR-SILK-SLIP-BLK"),
    image: "/products/dress-silk-black.jpg",
    hoverImage: "/products/dress-silk-black.jpg",
    images: ["/products/dress-silk-black.jpg"],
    style: ["romantic", "sexy", "chic", "glam"],
    occasion: ["hẹn hò", "đi tiệc", "sự kiện"],
    material: "Lụa satin tơ tằm bóng nhẹ mềm rũ",
    fit: "Slim bias-cut fit with side slit",
    silhouette: "column",
    lengthClass: "midi",
    neckline: "cowl",
    sleeveLength: "sleeveless",
    featured: true,
    isNew: true,
    active: true,
    sourceType: "retailer-corroborated",
    sourceUpdatedAt: "2026-10-02",
    tryOnCategory: "one-pieces",
    tryOnPhotoType: "flat-lay",
    tryOnImage: "/products/dress-silk-black.jpg",
    pattern: "solid",
    season: ["spring", "summer", "autumn"],
    formality: 5,
    warmth: 1,
    stretch: 2,
    coverage: 3,
    colorTemperature: "neutral",
    styleKeywords: ["đầm lụa đen", "đầm midi", "hai dây", "xẻ tà", "hẹn hò", "sang trọng"],
    aiSearchText: "đầm lụa đen hai dây xẻ tà dáng midi sang trọng hẹn hò đi tiệc quyến rũ",
    analyzerReady: true
  },
  {
    id: "lsoul-silk-slip-dress-red",
    sku: "DR-SILK-SLIP-RED",
    groupCode: "DR-SILK-SLIP",
    name: "Silk Slip Midi Dress",
    subtitle: "Đầm lụa hai dây xẻ tà màu đỏ rượu kiêu kỳ và nổi bật (Đỏ rượu)",
    category: "dress",
    type: "midi-dress",
    gender: "women",
    price: 1950000,
    color: "Đỏ rượu",
    colorFamily: "red",
    colorHex: "#7C1A2E",
    sizes,
    stock: 40,
    stockTracked: true,
    variants: variants("DR-SILK-SLIP-RED"),
    image: "/products/dress-silk-slip-red.jpg",
    hoverImage: "/products/dress-silk-slip-red.jpg",
    images: ["/products/dress-silk-slip-red.jpg"],
    style: ["romantic", "sexy", "glam"],
    occasion: ["hẹn hò", "đi tiệc", "sự kiện"],
    material: "Lụa satin tơ tằm bóng nhẹ mềm rũ",
    fit: "Slim bias-cut fit with side slit",
    silhouette: "column",
    lengthClass: "midi",
    neckline: "cowl",
    sleeveLength: "sleeveless",
    featured: true,
    isNew: true,
    active: true,
    sourceType: "retailer-corroborated",
    sourceUpdatedAt: "2026-10-02",
    tryOnCategory: "one-pieces",
    tryOnPhotoType: "flat-lay",
    tryOnImage: "/products/dress-silk-slip-red.jpg",
    pattern: "solid",
    season: ["spring", "summer", "autumn"],
    formality: 5,
    warmth: 1,
    stretch: 2,
    coverage: 3,
    colorTemperature: "warm",
    styleKeywords: ["đầm lụa đỏ", "đỏ burgundy", "hai dây", "xẻ tà", "nổi bật"],
    aiSearchText: "đầm lụa đỏ rượu hai dây xẻ tà quyến rũ kiêu kỳ đi tiệc hẹn hò",
    analyzerReady: true
  },
  {
    id: "lsoul-silk-slip-dress-navy",
    sku: "DR-SILK-SLIP-NVY",
    groupCode: "DR-SILK-SLIP",
    name: "Silk Slip Midi Dress",
    subtitle: "Đầm lụa hai dây xẻ tà tone xanh navy hoàng gia quyền quý (Xanh navy)",
    category: "dress",
    type: "midi-dress",
    gender: "women",
    price: 1950000,
    color: "Xanh navy",
    colorFamily: "navy",
    colorHex: "#1B2A47",
    sizes,
    stock: 35,
    stockTracked: true,
    variants: variants("DR-SILK-SLIP-NVY"),
    image: "/products/dress-silk-slip-navy.jpg",
    hoverImage: "/products/dress-silk-slip-navy.jpg",
    images: ["/products/dress-silk-slip-navy.jpg"],
    style: ["elegant", "glam"],
    occasion: ["sự kiện", "đi tiệc", "hẹn hò"],
    material: "Lụa satin mềm rũ",
    fit: "Slim bias-cut fit with side slit",
    silhouette: "column",
    lengthClass: "midi",
    neckline: "cowl",
    sleeveLength: "sleeveless",
    featured: false,
    isNew: true,
    active: true,
    sourceType: "retailer-corroborated",
    sourceUpdatedAt: "2026-10-02",
    tryOnCategory: "one-pieces",
    tryOnPhotoType: "flat-lay",
    tryOnImage: "/products/dress-silk-slip-navy.jpg",
    pattern: "solid",
    season: ["spring", "summer", "autumn"],
    formality: 5,
    warmth: 1,
    stretch: 2,
    coverage: 3,
    colorTemperature: "cool",
    styleKeywords: ["đầm lụa navy", "xanh đậm", "hai dây", "dạ tiệc"],
    aiSearchText: "đầm lụa xanh navy hai dây dự tiệc đêm sang trọng thanh tao",
    analyzerReady: true
  },

  // =========================================================================
  // 8. Classic Poplin Oversized Shirt (3 màu: Trắng, Xanh pastel, Đen)
  // =========================================================================
  {
    id: "lsoul-poplin-shirt-white",
    sku: "TP-POPLIN-SHIRT-WHT",
    groupCode: "TP-POPLIN-SHIRT",
    name: "Classic Poplin Oversized Shirt",
    subtitle: "Áo sơ mi poplin dáng rộng basic dễ phối theo style giấu quần hoặc khoác ngoài (Trắng)",
    category: "tops",
    type: "shirt",
    gender: "women",
    price: 920000,
    color: "Trắng",
    colorFamily: "white",
    colorHex: "#FFFFFF",
    sizes,
    stock: 80,
    stockTracked: true,
    variants: variants("TP-POPLIN-SHIRT-WHT"),
    image: "/products/shirt-poplin-white.jpg",
    hoverImage: "/products/shirt-poplin-white.jpg",
    images: ["/products/shirt-poplin-white.jpg"],
    style: ["minimal", "công sở", "casual", "streetwear"],
    occasion: ["đi làm", "đi học", "đi cafe", "đi chơi"],
    material: "100% Poplin cotton mềm mịn thoáng mát",
    fit: "Oversized boyfriend fit",
    silhouette: "relaxed",
    lengthClass: "mid",
    neckline: "collar",
    sleeveLength: "long",
    featured: true,
    isNew: true,
    active: true,
    sourceType: "retailer-corroborated",
    sourceUpdatedAt: "2026-10-02",
    tryOnCategory: "tops",
    tryOnPhotoType: "flat-lay",
    tryOnImage: "/products/shirt-poplin-white.jpg",
    pattern: "solid",
    season: ["all-season"],
    formality: 3,
    warmth: 2,
    stretch: 1,
    coverage: 4,
    colorTemperature: "neutral",
    styleKeywords: ["áo sơ mi trắng", "sơ mi form rộng", "poplin", "basic", "đi làm"],
    aiSearchText: "áo sơ mi trắng form rộng oversize poplin cotton thanh lịch đi làm đi chơi phối layer",
    analyzerReady: true
  },
  {
    id: "lsoul-poplin-shirt-blue",
    sku: "TP-POPLIN-SHIRT-BLU",
    groupCode: "TP-POPLIN-SHIRT",
    name: "Classic Poplin Oversized Shirt",
    subtitle: "Áo sơ mi poplin dáng rộng tone xanh pastel mát mắt thanh lịch (Xanh pastel)",
    category: "tops",
    type: "shirt",
    gender: "women",
    price: 920000,
    color: "Xanh pastel",
    colorFamily: "blue",
    colorHex: "#BFD7ED",
    sizes,
    stock: 60,
    stockTracked: true,
    variants: variants("TP-POPLIN-SHIRT-BLU"),
    image: "/products/shirt-poplin-blue.jpg",
    hoverImage: "/products/shirt-poplin-blue.jpg",
    images: ["/products/shirt-poplin-blue.jpg"],
    style: ["minimal", "công sở", "chic"],
    occasion: ["đi làm", "đi cafe"],
    material: "100% Poplin cotton mềm",
    fit: "Oversized boyfriend fit",
    silhouette: "relaxed",
    lengthClass: "mid",
    neckline: "collar",
    sleeveLength: "long",
    featured: false,
    isNew: true,
    active: true,
    sourceType: "retailer-corroborated",
    sourceUpdatedAt: "2026-10-02",
    tryOnCategory: "tops",
    tryOnPhotoType: "flat-lay",
    tryOnImage: "/products/shirt-poplin-blue.jpg",
    pattern: "solid",
    season: ["all-season"],
    formality: 3,
    warmth: 2,
    stretch: 1,
    coverage: 4,
    colorTemperature: "cool",
    styleKeywords: ["áo sơ mi xanh", "xanh nhạt", "pastel", "công sở"],
    aiSearchText: "áo sơ mi xanh pastel form rộng thanh lịch nhẹ nhàng đi làm",
    analyzerReady: true
  },
  {
    id: "lsoul-poplin-shirt-black",
    sku: "TP-POPLIN-SHIRT-BLK",
    groupCode: "TP-POPLIN-SHIRT",
    name: "Classic Poplin Oversized Shirt",
    subtitle: "Áo sơ mi poplin dáng rộng tone đen cá tính thời thượng (Đen)",
    category: "tops",
    type: "shirt",
    gender: "women",
    price: 920000,
    color: "Đen",
    colorFamily: "black",
    colorHex: "#151515",
    sizes,
    stock: 55,
    stockTracked: true,
    variants: variants("TP-POPLIN-SHIRT-BLK"),
    image: "/products/shirt-poplin-black.jpg",
    hoverImage: "/products/shirt-poplin-black.jpg",
    images: ["/products/shirt-poplin-black.jpg"],
    style: ["edgy", "minimal", "streetwear"],
    occasion: ["đi chơi", "đi cafe", "concert"],
    material: "100% Poplin cotton dệt dày dặn",
    fit: "Oversized boyfriend fit",
    silhouette: "relaxed",
    lengthClass: "mid",
    neckline: "collar",
    sleeveLength: "long",
    featured: false,
    isNew: true,
    active: true,
    sourceType: "retailer-corroborated",
    sourceUpdatedAt: "2026-10-02",
    tryOnCategory: "tops",
    tryOnPhotoType: "flat-lay",
    tryOnImage: "/products/shirt-poplin-black.jpg",
    pattern: "solid",
    season: ["all-season"],
    formality: 3,
    warmth: 2,
    stretch: 1,
    coverage: 4,
    colorTemperature: "neutral",
    styleKeywords: ["áo sơ mi đen", "sơ mi oversize", "cá tính"],
    aiSearchText: "áo sơ mi đen form rộng cá tính phối khoác ngoài năng động",
    analyzerReady: true
  },

  // =========================================================================
  // 9. Y2K Low-Rise Flare Denim Jeans (3 màu: Xanh denim, Đen washed, Trắng)
  // =========================================================================
  {
    id: "lsoul-flare-jeans-denim",
    sku: "PT-Y2K-FLARE-BLU",
    groupCode: "PT-Y2K-FLARE",
    name: "Y2K Low-Rise Flare Jeans",
    subtitle: "Quần jeans ống loe cạp trễ kéo dài chân theo chuẩn phong cách Y2K (Xanh denim)",
    category: "bottoms",
    type: "flare-pants",
    gender: "women",
    price: 1550000,
    color: "Xanh denim",
    colorFamily: "blue",
    colorHex: "#395C82",
    sizes,
    stock: 60,
    stockTracked: true,
    variants: variants("PT-Y2K-FLARE-BLU"),
    image: "/products/pants-flare-denim-blue.jpg",
    hoverImage: "/products/pants-flare-denim-blue.jpg",
    images: ["/products/pants-flare-denim-blue.jpg"],
    style: ["Y2K", "streetwear", "edgy"],
    occasion: ["đi chơi", "concert", "cafe"],
    material: "Denim cotton pha spandex co giãn nhẹ thoải mái",
    fit: "Low-rise flared leg",
    silhouette: "flare",
    lengthClass: "maxi",
    waistRise: "low",
    featured: true,
    isNew: true,
    active: true,
    sourceType: "retailer-corroborated",
    sourceUpdatedAt: "2026-10-02",
    tryOnCategory: "bottoms",
    tryOnPhotoType: "flat-lay",
    tryOnImage: "/products/pants-flare-denim-blue.jpg",
    pattern: "denim",
    season: ["all-season"],
    formality: 2,
    warmth: 3,
    stretch: 2,
    coverage: 5,
    colorTemperature: "cool",
    styleKeywords: ["quần jeans ống loe", "quần cạp trễ", "Y2K", "denim", "hack chân"],
    aiSearchText: "quần jeans ống loe cạp trễ màu xanh denim Y2K kéo dài chân cá tính",
    analyzerReady: true
  },
  {
    id: "lsoul-flare-jeans-black",
    sku: "PT-Y2K-FLARE-BLK",
    groupCode: "PT-Y2K-FLARE",
    name: "Y2K Low-Rise Flare Jeans",
    subtitle: "Quần jeans ống loe cạp trễ màu đen washed cá tính cực tôn vòng 3 (Đen washed)",
    category: "bottoms",
    type: "flare-pants",
    gender: "women",
    price: 1550000,
    color: "Đen",
    colorFamily: "black",
    colorHex: "#222222",
    sizes,
    stock: 55,
    stockTracked: true,
    variants: variants("PT-Y2K-FLARE-BLK"),
    image: "/products/pants-flare-denim-black.jpg",
    hoverImage: "/products/pants-flare-denim-black.jpg",
    images: ["/products/pants-flare-denim-black.jpg"],
    style: ["Y2K", "edgy", "gothic"],
    occasion: ["đi chơi", "concert", "party"],
    material: "Denim cotton đen wash mềm",
    fit: "Low-rise flared leg",
    silhouette: "flare",
    lengthClass: "maxi",
    waistRise: "low",
    featured: true,
    isNew: true,
    active: true,
    sourceType: "retailer-corroborated",
    sourceUpdatedAt: "2026-10-02",
    tryOnCategory: "bottoms",
    tryOnPhotoType: "flat-lay",
    tryOnImage: "/products/pants-flare-denim-black.jpg",
    pattern: "solid",
    season: ["all-season"],
    formality: 2,
    warmth: 3,
    stretch: 2,
    coverage: 5,
    colorTemperature: "neutral",
    styleKeywords: ["quần jeans đen ống loe", "quần cạp trễ đen", "Y2K", "cá tính"],
    aiSearchText: "quần jeans đen ống loe cạp trễ hack eo tôn mông cá tính concert",
    analyzerReady: true
  },
  {
    id: "lsoul-flare-jeans-white",
    sku: "PT-Y2K-FLARE-WHT",
    groupCode: "PT-Y2K-FLARE",
    name: "Y2K Low-Rise Flare Jeans",
    subtitle: "Quần jeans ống loe cạp trễ tone trắng sáng phong cách clean fit (Trắng)",
    category: "bottoms",
    type: "flare-pants",
    gender: "women",
    price: 1550000,
    color: "Trắng",
    colorFamily: "white",
    colorHex: "#FAF9F6",
    sizes,
    stock: 40,
    stockTracked: true,
    variants: variants("PT-Y2K-FLARE-WHT"),
    image: "/products/pants-flare-denim-white.jpg",
    hoverImage: "/products/pants-flare-denim-white.jpg",
    images: ["/products/pants-flare-denim-white.jpg"],
    style: ["clean fit", "Y2K", "nữ tính"],
    occasion: ["đi cafe", "đi chơi", "du lịch"],
    material: "Denim trắng dệt chắc tay",
    fit: "Low-rise flared leg",
    silhouette: "flare",
    lengthClass: "maxi",
    waistRise: "low",
    featured: false,
    isNew: true,
    active: true,
    sourceType: "retailer-corroborated",
    sourceUpdatedAt: "2026-10-02",
    tryOnCategory: "bottoms",
    tryOnPhotoType: "flat-lay",
    tryOnImage: "/products/pants-flare-denim-white.jpg",
    pattern: "solid",
    season: ["spring", "summer"],
    formality: 2,
    warmth: 3,
    stretch: 2,
    coverage: 5,
    colorTemperature: "neutral",
    styleKeywords: ["quần jeans trắng", "quần ống loe trắng", "clean fit"],
    aiSearchText: "quần jeans trắng ống loe cạp trễ sang xịn phong cách clean fit",
    analyzerReady: true
  },

  // =========================================================================
  // 10. A-Line Minimalist Slit Midi Skirt (3 màu: Đen, Be kem, Nâu)
  // =========================================================================
  {
    id: "lsoul-aline-slit-skirt-black",
    sku: "SK-ALINE-SLIT-BLK",
    groupCode: "SK-ALINE-SLIT",
    name: "A-Line Slit Midi Skirt",
    subtitle: "Chân váy chữ A dáng midi xẻ tà cạp cao thanh lịch tôn eo thon (Đen)",
    category: "bottoms",
    type: "skirt",
    gender: "women",
    price: 990000,
    color: "Đen",
    colorFamily: "black",
    colorHex: "#111111",
    sizes,
    stock: 55,
    stockTracked: true,
    variants: variants("SK-ALINE-SLIT-BLK"),
    image: "/products/skirt-slit-midi-black.jpg",
    hoverImage: "/products/skirt-slit-midi-black.jpg",
    images: ["/products/skirt-slit-midi-black.jpg"],
    style: ["minimal", "công sở", "chic"],
    occasion: ["đi làm", "hẹn hò", "đi cafe"],
    material: "Vải dệt tổng hợp đứng form có xẻ tà trước",
    fit: "High-waist A-line with front slit",
    silhouette: "a-line",
    lengthClass: "midi",
    waistRise: "high",
    featured: false,
    isNew: true,
    active: true,
    sourceType: "retailer-corroborated",
    sourceUpdatedAt: "2026-10-02",
    tryOnCategory: "bottoms",
    tryOnPhotoType: "flat-lay",
    tryOnImage: "/products/skirt-slit-midi-black.jpg",
    pattern: "solid",
    season: ["all-season"],
    formality: 4,
    warmth: 2,
    stretch: 2,
    coverage: 4,
    colorTemperature: "neutral",
    styleKeywords: ["chân váy đen dài", "chân váy midi", "xẻ tà", "chữ A", "công sở"],
    aiSearchText: "chân váy đen midi chữ A xẻ tà cạp cao tôn dáng đi làm hẹn hò thanh lịch",
    analyzerReady: true
  },
  {
    id: "lsoul-aline-slit-skirt-beige",
    sku: "SK-ALINE-SLIT-BEI",
    groupCode: "SK-ALINE-SLIT",
    name: "A-Line Slit Midi Skirt",
    subtitle: "Chân váy chữ A dáng midi xẻ tà tone be thanh tao nhã nhặn (Be kem)",
    category: "bottoms",
    type: "skirt",
    gender: "women",
    price: 990000,
    color: "Be",
    colorFamily: "beige",
    colorHex: "#EFEBD9",
    sizes,
    stock: 50,
    stockTracked: true,
    variants: variants("SK-ALINE-SLIT-BEI"),
    image: "/products/skirt-slit-midi-beige.jpg",
    hoverImage: "/products/skirt-slit-midi-beige.jpg",
    images: ["/products/skirt-slit-midi-beige.jpg"],
    style: ["minimal", "công sở", "nữ tính"],
    occasion: ["đi làm", "cafe", "hẹn hò"],
    material: "Vải dệt cao cấp mềm rũ",
    fit: "High-waist A-line with front slit",
    silhouette: "a-line",
    lengthClass: "midi",
    waistRise: "high",
    featured: false,
    isNew: true,
    active: true,
    sourceType: "retailer-corroborated",
    sourceUpdatedAt: "2026-10-02",
    tryOnCategory: "bottoms",
    tryOnPhotoType: "flat-lay",
    tryOnImage: "/products/skirt-slit-midi-beige.jpg",
    pattern: "solid",
    season: ["spring", "summer", "autumn"],
    formality: 4,
    warmth: 2,
    stretch: 2,
    coverage: 4,
    colorTemperature: "warm",
    styleKeywords: ["chân váy be", "chân váy midi", "xẻ tà", "nhã nhặn"],
    aiSearchText: "chân váy be midi xẻ tà chữ A nhẹ nhàng thanh lịch đi làm",
    analyzerReady: true
  },
  {
    id: "lsoul-aline-slit-skirt-brown",
    sku: "SK-ALINE-SLIT-BRN",
    groupCode: "SK-ALINE-SLIT",
    name: "A-Line Slit Midi Skirt",
    subtitle: "Chân váy chữ A dáng midi xẻ tà tone nâu ấm quý phái (Nâu)",
    category: "bottoms",
    type: "skirt",
    gender: "women",
    price: 990000,
    color: "Nâu",
    colorFamily: "brown",
    colorHex: "#5B3A29",
    sizes,
    stock: 40,
    stockTracked: true,
    variants: variants("SK-ALINE-SLIT-BRN"),
    image: "/products/skirt-slit-midi-brown.jpg",
    hoverImage: "/products/skirt-slit-midi-brown.jpg",
    images: ["/products/skirt-slit-midi-brown.jpg"],
    style: ["vintage", "chic"],
    occasion: ["đi làm", "mua sắm"],
    material: "Vải dệt đứng form",
    fit: "High-waist A-line with front slit",
    silhouette: "a-line",
    lengthClass: "midi",
    waistRise: "high",
    featured: false,
    isNew: true,
    active: true,
    sourceType: "retailer-corroborated",
    sourceUpdatedAt: "2026-10-02",
    tryOnCategory: "bottoms",
    tryOnPhotoType: "flat-lay",
    tryOnImage: "/products/skirt-slit-midi-brown.jpg",
    pattern: "solid",
    season: ["autumn", "winter"],
    formality: 4,
    warmth: 2,
    stretch: 2,
    coverage: 4,
    colorTemperature: "warm",
    styleKeywords: ["chân váy nâu", "chân váy midi", "xẻ tà"],
    aiSearchText: "chân váy nâu midi chữ A thu đông quý phái sang trọng",
    analyzerReady: true
  },

  // =========================================================================
  // 11. Seamless Halter Knit Bodysuit (3 màu: Đen, Trắng, Đỏ rượu)
  // =========================================================================
  {
    id: "lsoul-seamless-halter-bodysuit-black",
    sku: "TP-HALTER-BODY-BLK",
    groupCode: "TP-HALTER-BODY",
    name: "Seamless Halter Bodysuit",
    subtitle: "Áo bodysuit cổ yếm không đường may ôm sát tôn đường cong quyến rũ (Đen)",
    category: "tops",
    type: "bodysuit",
    gender: "women",
    price: 850000,
    color: "Đen",
    colorFamily: "black",
    colorHex: "#111111",
    sizes,
    stock: 65,
    stockTracked: true,
    variants: variants("TP-HALTER-BODY-BLK"),
    image: "/products/top-halter-bodysuit-black.jpg",
    hoverImage: "/products/top-halter-bodysuit-black.jpg",
    images: ["/products/top-halter-bodysuit-black.jpg"],
    style: ["sexy", "minimal", "Y2K"],
    occasion: ["đi tiệc", "concert", "bar", "đi chơi"],
    material: "Polyamide pha elastane co giãn 4 chiều định hình cơ thể",
    fit: "Fitted seamless bodycon",
    silhouette: "fitted",
    lengthClass: "crop",
    neckline: "halter",
    sleeveLength: "sleeveless",
    featured: true,
    isNew: true,
    active: true,
    sourceType: "retailer-corroborated",
    sourceUpdatedAt: "2026-10-02",
    tryOnCategory: "tops",
    tryOnPhotoType: "flat-lay",
    tryOnImage: "/products/top-halter-bodysuit-black.jpg",
    pattern: "solid",
    season: ["spring", "summer", "autumn"],
    formality: 3,
    warmth: 1,
    stretch: 5,
    coverage: 2,
    colorTemperature: "neutral",
    styleKeywords: ["áo bodysuit đen", "cổ yếm", "ôm sát", "sexy", "tôn eo"],
    aiSearchText: "áo bodysuit đen cổ yếm thun ôm sát tôn dáng phối chân váy quần jeans",
    analyzerReady: true
  },
  {
    id: "lsoul-seamless-halter-bodysuit-white",
    sku: "TP-HALTER-BODY-WHT",
    groupCode: "TP-HALTER-BODY",
    name: "Seamless Halter Bodysuit",
    subtitle: "Áo bodysuit cổ yếm không đường may màu trắng tinh khôi gợi cảm (Trắng)",
    category: "tops",
    type: "bodysuit",
    gender: "women",
    price: 850000,
    color: "Trắng",
    colorFamily: "white",
    colorHex: "#FFFFFF",
    sizes,
    stock: 60,
    stockTracked: true,
    variants: variants("TP-HALTER-BODY-WHT"),
    image: "/products/top-halter-bodysuit-white.jpg",
    hoverImage: "/products/top-halter-bodysuit-white.jpg",
    images: ["/products/top-halter-bodysuit-white.jpg"],
    style: ["sexy", "minimal", "clean fit"],
    occasion: ["đi chơi", "hẹn hò", "đi cafe"],
    material: "Polyamide pha elastane co giãn 4 chiều",
    fit: "Fitted seamless bodycon",
    silhouette: "fitted",
    lengthClass: "crop",
    neckline: "halter",
    sleeveLength: "sleeveless",
    featured: false,
    isNew: true,
    active: true,
    sourceType: "retailer-corroborated",
    sourceUpdatedAt: "2026-10-02",
    tryOnCategory: "tops",
    tryOnPhotoType: "flat-lay",
    tryOnImage: "/products/top-halter-bodysuit-white.jpg",
    pattern: "solid",
    season: ["spring", "summer"],
    formality: 3,
    warmth: 1,
    stretch: 5,
    coverage: 2,
    colorTemperature: "neutral",
    styleKeywords: ["áo bodysuit trắng", "cổ yếm", "clean fit"],
    aiSearchText: "áo bodysuit trắng cổ yếm gợi cảm tôn dáng phối đồ mùa hè",
    analyzerReady: true
  },
  {
    id: "lsoul-seamless-halter-bodysuit-red",
    sku: "TP-HALTER-BODY-RED",
    groupCode: "TP-HALTER-BODY",
    name: "Seamless Halter Bodysuit",
    subtitle: "Áo bodysuit cổ yếm tone đỏ rượu kiêu kỳ và bùng nổ năng lượng (Đỏ)",
    category: "tops",
    type: "bodysuit",
    gender: "women",
    price: 850000,
    color: "Đỏ",
    colorFamily: "red",
    colorHex: "#8B182B",
    sizes,
    stock: 50,
    stockTracked: true,
    variants: variants("TP-HALTER-BODY-RED"),
    image: "/products/top-halter-bodysuit-red.jpg",
    hoverImage: "/products/top-halter-bodysuit-red.jpg",
    images: ["/products/top-halter-bodysuit-red.jpg"],
    style: ["sexy", "glam", "statement"],
    occasion: ["đi tiệc", "bar", "concert"],
    material: "Polyamide pha elastane co giãn định hình",
    fit: "Fitted seamless bodycon",
    silhouette: "fitted",
    lengthClass: "crop",
    neckline: "halter",
    sleeveLength: "sleeveless",
    featured: true,
    isNew: true,
    active: true,
    sourceType: "retailer-corroborated",
    sourceUpdatedAt: "2026-10-02",
    tryOnCategory: "tops",
    tryOnPhotoType: "flat-lay",
    tryOnImage: "/products/top-halter-bodysuit-red.jpg",
    pattern: "solid",
    season: ["spring", "summer", "autumn"],
    formality: 4,
    warmth: 1,
    stretch: 5,
    coverage: 2,
    colorTemperature: "warm",
    styleKeywords: ["áo bodysuit đỏ", "đỏ rượu", "cổ yếm", "nổi bật"],
    aiSearchText: "áo bodysuit đỏ rượu cổ yếm nổi bật đi bar party tiệc đêm",
    analyzerReady: true
  },

  // =========================================================================
  // 12. Strapless Satin Mini Bodycon Dress (3 màu: Đen, Trắng, Đỏ rượu)
  // =========================================================================
  {
    id: "lsoul-strapless-mini-dress-black",
    sku: "DR-STRAPLESS-MINI-BLK",
    groupCode: "DR-STRAPLESS-MINI",
    name: "Strapless Satin Mini Bodycon Dress",
    subtitle: "Đầm mini cúp ngực quây ôm body chất satin lụa bóng kiêu kỳ (Đen)",
    category: "dress",
    type: "bodycon-dress",
    gender: "women",
    price: 1650000,
    color: "Đen",
    colorFamily: "black",
    colorHex: "#111111",
    sizes,
    stock: 50,
    stockTracked: true,
    variants: variants("DR-STRAPLESS-MINI-BLK"),
    image: "/products/dress-strapless-mini-black.jpg",
    hoverImage: "/products/dress-strapless-mini-black.jpg",
    images: ["/products/dress-strapless-mini-black.jpg"],
    style: ["sexy", "glam", "statement", "minimal"],
    occasion: ["đi tiệc", "clubbing", "hẹn hò"],
    material: "Satin lụa co giãn cao cấp",
    fit: "Body-hugging mini fit",
    silhouette: "bodycon",
    lengthClass: "mini",
    neckline: "strapless",
    sleeveLength: "sleeveless",
    featured: true,
    isNew: true,
    active: true,
    sourceType: "retailer-corroborated",
    sourceUpdatedAt: "2026-10-02",
    tryOnCategory: "one-pieces",
    tryOnPhotoType: "flat-lay",
    tryOnImage: "/products/dress-strapless-mini-black.jpg",
    pattern: "solid",
    season: ["spring", "summer"],
    formality: 4,
    warmth: 1,
    stretch: 3,
    coverage: 2,
    colorTemperature: "neutral",
    styleKeywords: ["đầm quây đen", "đầm mini ôm body", "cúp ngực", "váy ngắn đen"],
    aiSearchText: "đầm quây cúp ngực mini ôm body màu đen satin đi tiệc bar sexy",
    analyzerReady: true
  },
  {
    id: "lsoul-strapless-mini-dress-white",
    sku: "DR-STRAPLESS-MINI-WHT",
    groupCode: "DR-STRAPLESS-MINI",
    name: "Strapless Satin Mini Bodycon Dress",
    subtitle: "Đầm mini cúp ngực quây ôm body tone trắng ngọc ngà gợi cảm (Trắng)",
    category: "dress",
    type: "bodycon-dress",
    gender: "women",
    price: 1650000,
    color: "Trắng",
    colorFamily: "white",
    colorHex: "#FFFFFF",
    sizes,
    stock: 45,
    stockTracked: true,
    variants: variants("DR-STRAPLESS-MINI-WHT"),
    image: "/products/dress-strapless-mini-white.jpg",
    hoverImage: "/products/dress-strapless-mini-white.jpg",
    images: ["/products/dress-strapless-mini-white.jpg"],
    style: ["romantic", "sexy", "nữ tính"],
    occasion: ["đi tiệc", "hẹn hò", "sinh nhật"],
    material: "Satin lụa co giãn có lót chống lộ",
    fit: "Body-hugging mini fit",
    silhouette: "bodycon",
    lengthClass: "mini",
    neckline: "strapless",
    sleeveLength: "sleeveless",
    featured: false,
    isNew: true,
    active: true,
    sourceType: "retailer-corroborated",
    sourceUpdatedAt: "2026-10-02",
    tryOnCategory: "one-pieces",
    tryOnPhotoType: "flat-lay",
    tryOnImage: "/products/dress-strapless-mini-white.jpg",
    pattern: "solid",
    season: ["spring", "summer"],
    formality: 4,
    warmth: 1,
    stretch: 3,
    coverage: 2,
    colorTemperature: "neutral",
    styleKeywords: ["đầm quây trắng", "đầm mini body trắng", "sinh nhật"],
    aiSearchText: "đầm quây cúp ngực màu trắng ôm body mini satin tiệc sinh nhật quyến rũ",
    analyzerReady: true
  },
  {
    id: "lsoul-strapless-mini-dress-red",
    sku: "DR-STRAPLESS-MINI-RED",
    groupCode: "DR-STRAPLESS-MINI",
    name: "Strapless Satin Mini Bodycon Dress",
    subtitle: "Đầm mini cúp ngực quây ôm body sắc đỏ nồng cháy thiêu đốt ánh nhìn (Đỏ)",
    category: "dress",
    type: "bodycon-dress",
    gender: "women",
    price: 1650000,
    color: "Đỏ",
    colorFamily: "red",
    colorHex: "#A01B30",
    sizes,
    stock: 40,
    stockTracked: true,
    variants: variants("DR-STRAPLESS-MINI-RED"),
    image: "/products/dress-strapless-mini-red.jpg",
    hoverImage: "/products/dress-strapless-mini-red.jpg",
    images: ["/products/dress-strapless-mini-red.jpg"],
    style: ["sexy", "glam", "statement"],
    occasion: ["đi tiệc", "bar", "party"],
    material: "Satin lụa co giãn cao cấp",
    fit: "Body-hugging mini fit",
    silhouette: "bodycon",
    lengthClass: "mini",
    neckline: "strapless",
    sleeveLength: "sleeveless",
    featured: true,
    isNew: true,
    active: true,
    sourceType: "retailer-corroborated",
    sourceUpdatedAt: "2026-10-02",
    tryOnCategory: "one-pieces",
    tryOnPhotoType: "flat-lay",
    tryOnImage: "/products/dress-strapless-mini-red.jpg",
    pattern: "solid",
    season: ["spring", "summer"],
    formality: 4,
    warmth: 1,
    stretch: 3,
    coverage: 2,
    colorTemperature: "warm",
    styleKeywords: ["đầm quây đỏ", "đầm mini đỏ", "ôm body", "party"],
    aiSearchText: "đầm quây cúp ngực màu đỏ ôm body mini đi quẩy bar party nổi bật",
    analyzerReady: true
  },

  // =========================================================================
  // 13. High-Waist Tailored Tweed Shorts (2 màu: Đen, Trắng)
  // =========================================================================
  {
    id: "lsoul-tweed-shorts-black",
    sku: "PT-TWEED-SHORT-BLK",
    groupCode: "PT-TWEED-SHORT",
    name: "High-Waist Tailored Tweed Shorts",
    subtitle: "Quần short dạ tweed cạp cao đính cúc kim loại sang trọng (Đen)",
    category: "bottoms",
    type: "shorts",
    gender: "women",
    price: 950000,
    color: "Đen",
    colorFamily: "black",
    colorHex: "#111111",
    sizes,
    stock: 50,
    stockTracked: true,
    variants: variants("PT-TWEED-SHORT-BLK"),
    image: "/products/pants-tweed-shorts-black.jpg",
    hoverImage: "/products/pants-tweed-shorts-black.jpg",
    images: ["/products/pants-tweed-shorts-black.jpg"],
    style: ["chic", "glam", "nữ tính"],
    occasion: ["đi tiệc", "đi cafe", "hẹn hò"],
    material: "Dạ tweed dệt ánh kim có lót lụa êm ái",
    fit: "High-rise tailored shorts",
    silhouette: "structured",
    lengthClass: "mini",
    waistRise: "high",
    featured: false,
    isNew: true,
    active: true,
    sourceType: "retailer-corroborated",
    sourceUpdatedAt: "2026-10-02",
    tryOnCategory: "bottoms",
    tryOnPhotoType: "flat-lay",
    tryOnImage: "/products/pants-tweed-shorts-black.jpg",
    pattern: "tweed",
    season: ["autumn", "winter", "spring"],
    formality: 4,
    warmth: 3,
    stretch: 1,
    coverage: 2,
    colorTemperature: "neutral",
    styleKeywords: ["quần short dạ", "tweed đen", "cạp cao", "sang chảnh"],
    aiSearchText: "quần short dạ tweed đen cạp cao đính cúc sang trọng thu đông",
    analyzerReady: true
  },
  {
    id: "lsoul-tweed-shorts-white",
    sku: "PT-TWEED-SHORT-WHT",
    groupCode: "PT-TWEED-SHORT",
    name: "High-Waist Tailored Tweed Shorts",
    subtitle: "Quần short dạ tweed cạp cao tone trắng ngọc quý cô tiểu thư (Trắng)",
    category: "bottoms",
    type: "shorts",
    gender: "women",
    price: 950000,
    color: "Trắng",
    colorFamily: "white",
    colorHex: "#FFFFFF",
    sizes,
    stock: 45,
    stockTracked: true,
    variants: variants("PT-TWEED-SHORT-WHT"),
    image: "/products/pants-tweed-shorts-white.jpg",
    hoverImage: "/products/pants-tweed-shorts-white.jpg",
    images: ["/products/pants-tweed-shorts-white.jpg"],
    style: ["chic", "romantic", "tiểu thư"],
    occasion: ["đi cafe", "hẹn hò", "sự kiện"],
    material: "Dạ tweed dệt ánh kim có lót lụa êm ái",
    fit: "High-rise tailored shorts",
    silhouette: "structured",
    lengthClass: "mini",
    waistRise: "high",
    featured: false,
    isNew: true,
    active: true,
    sourceType: "retailer-corroborated",
    sourceUpdatedAt: "2026-10-02",
    tryOnCategory: "bottoms",
    tryOnPhotoType: "flat-lay",
    tryOnImage: "/products/pants-tweed-shorts-white.jpg",
    pattern: "tweed",
    season: ["autumn", "winter", "spring"],
    formality: 4,
    warmth: 3,
    stretch: 1,
    coverage: 2,
    colorTemperature: "neutral",
    styleKeywords: ["quần short trắng", "tweed trắng", "cạp cao", "tiểu thư"],
    aiSearchText: "quần short dạ tweed trắng cạp cao phong cách tiểu thư sang chảnh",
    analyzerReady: true
  }
];
